### ISSUE TITLE
space dev not working

### ISSUE THREAD

**Issue by appsdevpk** [tbdsux/space-custom-apps#7]
how can i develop locally using php custom app, space dev give the below output

![image](https://user-images.githubusercontent.com/516860/232218509-cb63cbcf-7987-486e-82e8-374dbbab4162.png)

**Comment by tbdsux** [comment]
please check the updated spacefiles for your reference

**Comment by appsdevpk** [comment]
Thanks, it worked

**Comment by tbdsux** [comment]
thank you... closing now :smiley:
